[phases.setup]
nixPkgs = ["...", "libGL", "libglib-2.0-0", "libsm6", "libxext6", "libxrender1", "libgomp1", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"