[phases.setup]
nixPkgs = ["python312", "gcc", "libGL", "glib", "xorg.libSM", "xorg.libXext", "xorg.libXrender"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"